# -*- coding: utf-8 -*-
"""Datos reales de controladores GESTOCK (autenticado en codigo fuente)."""

CONTROLADORES = [
    {
        "id": "auth",
        "titulo": "Autenticacion / Auth",
        "modulo": "auth",
        "desc": "Login, perfil, logout, cambio de contrasena y recuperacion de credenciales (solicitar, validar, restablecer).",
        "servicio": "auth.service.ts (backend) · auth.ts (frontend)",
        "reparar": "auth.service.ts → usuario.repo/sesion.repo/restablecimiento (SQL)",
        "tablas": "usuarios · sesiones · restablecimientos_contrasena",
        "coleccion": [
            ("POST", "/auth/login", "validateBody(loginSchema) + loginEmailLimiter + loginIpLimiter"),
            ("GET", "/auth/perfil", "authenticateToken"),
            ("POST", "/auth/logout", "authenticateToken"),
            ("PUT", "/auth/contrasena", "authenticateToken + validateBody(cambiarContrasenaSchema)"),
            ("POST", "/auth/recuperar", "recuperacionLimiter + validateBody(solicitarRecuperacionSchema)"),
            ("POST", "/auth/recuperar/validar", "validateBody(validarCodigoRecuperacionSchema)"),
            ("POST", "/auth/recuperar/restablecer", "validateBody(restablecerPasswordSchema)"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 credenciales/token invalidos",),
            ("403 usuario inactivo",),
            ("404 usuario no existe",),
            ("409 contrasena actual incorrecta",),
            ("429 rate limit",),
            ("500 error interno",),
        ],
        "ramas": [
            ("429 RATE_LIMITED", "¿Email supero 5 intentos/15min?", "Has superado el maximo de intentos para esta cuenta. Espera 15 minutos e intenta de nuevo."),
            ("429 RATE_LIMITED", "¿IP supero 60 peticiones/15min?", "Demasiadas solicitudes. Espera unos minutos e intenta de nuevo."),
            ("400 BAD_REQUEST", "¿loginSchema valida email+password?", "Los datos enviados no son validos."),
            ("401 UNAUTHORIZED", "¿Email+password correctos (bcrypt)?", "Las credenciales ingresadas no son validas."),
            ("401 UNAUTHORIZED", "¿Usuario pertenece a la empresa?", "El usuario no pertenece a esa empresa."),
            ("401 UNAUTHORIZED", "¿Contrasena actual correcta (PUT /contrasena)?", "La contrasena actual no es correcta."),
            ("401 UNAUTHORIZED", "¿Codigo de recuperacion valido?", "El codigo ingresado no es valido o ha expirado."),
            ("403 FORBIDDEN", "¿Cuenta activa (login/perfil)?", "Tu cuenta esta inactiva. Contacta al administrador."),
            ("403 FORBIDDEN", "¿Rol asignado activo?", "El rol asignado a tu cuenta esta inactivo. Contacta al administrador."),
            ("404 NOT_FOUND", "¿Existe el usuario (perfil/password)?", "El usuario no existe."),
            ("500 INTERNAL_ERROR", "¿Se cargaron los permisos al iniciar?", "No se pudieron cargar los permisos del usuario."),
        ],
    },
    {
        "id": "usuario",
        "titulo": "Usuarios / Usuarios",
        "modulo": "usuario",
        "desc": "CRUD de usuarios: listar, detalle, crear, actualizar, activar/desactivar, cambiar rol, password, eliminar.",
        "servicio": "usuario.service.ts (frontend) · usuario.repo.ts (backend)",
        "reparar": "usuario.repo.ts (CRUD SQL + filtros + paginacion)",
        "tablas": "usuarios · roles · empresas",
        "coleccion": [
            ("GET", "/usuarios", "authorizePermission('usuarios.view')"),
            ("GET", "/usuarios/:id", "authorizePermission('usuarios.view') + validateParams"),
            ("POST", "/usuarios", "authorizePermission('usuarios.create') + validateBody"),
            ("PUT", "/usuarios/:id", "authorizePermission('usuarios.edit') + validateBody + validateParams"),
            ("PATCH", "/usuarios/:id/estado", "authorizePermission('usuarios.desactivar')"),
            ("PATCH", "/usuarios/:id/rol", "authorizePermission('usuarios.edit') + validateBody"),
            ("PUT", "/usuarios/:id/password", "authorizePermission('usuarios.password') + validateBody"),
            ("DELETE", "/usuarios/:id", "authorizePermission('usuarios.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 usuario no existe",),
            ("409 email duplicado / FK",),
            ("500 error interno",),
        ],
        "ramas": [
            ("409 CONFLICT", "¿Ya existe un usuario con ese email?", "Ya existe un usuario con ese correo electronico."),
            ("404 NOT_FOUND", "¿Existe el rol seleccionado (POST/PUT/rol)?", "El rol seleccionado no existe."),
            ("404 NOT_FOUND", "¿Existe el usuario solicitado?", "El usuario no existe."),
            ("400 BAD_REQUEST", "¿Cambias tu propia contrasena (PUT /:id/password)?", "Para cambiar tu propia contrasena usa la opcion de tu perfil."),
            ("403 FORBIDDEN", "¿Eliminas tu propio usuario (DELETE)?", "No puedes eliminar tu propio usuario."),
        ],
    },
    {
        "id": "rol",
        "titulo": "Roles / Roles",
        "modulo": "rol",
        "desc": "CRUD de roles + asignacion de permisos (RBAC): listar, basico, detalle, crear, actualizar, estado, permisos.",
        "servicio": "rol.service.ts (frontend) · rol.repo.ts (backend)",
        "reparar": "rol.repo.ts (CRUD + rol_permiso + usuarios por rol)",
        "tablas": "roles · rol_permiso · permisos · usuarios",
        "coleccion": [
            ("GET", "/roles/basicos", "authorizePermission('roles.view')"),
            ("GET", "/roles", "authorizePermission('roles.view')"),
            ("GET", "/roles/:id", "authorizePermission('roles.view') + validateParams"),
            ("POST", "/roles", "authorizePermission('roles.create') + validateBody"),
            ("PUT", "/roles/:id", "authorizePermission('roles.edit') + validateBody"),
            ("PATCH", "/roles/:id/estado", "authorizePermission('roles.edit') + validateBody"),
            ("PUT", "/roles/:id/permisos", "authorizePermission('roles.asignar_permisos') + validateBody"),
            ("DELETE", "/roles/:id", "authorizePermission('roles.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 rol no existe",),
            ("409 nombre duplicado / FK usuarios",),
            ("500 error interno",),
        ],
        "ramas": [
            ("409 CONFLICT", "¿Ya existe un rol con ese nombre?", "Ya existe un rol con ese nombre."),
            ("404 NOT_FOUND", "¿Existe el rol solicitado?", "El rol no existe."),
            ("409 CONFLICT", "¿El rol tiene usuarios asignados (DELETE)?", "No se puede eliminar un rol que tiene usuarios asignados."),
        ],
    },
    {
        "id": "permiso",
        "titulo": "Permisos / Permisos",
        "modulo": "permiso",
        "desc": "Catalogo de permisos: listar todos y listar por modulo.",
        "servicio": "permiso.service.ts (frontend) · permiso.repo.ts (backend)",
        "reparar": "permiso.repo.ts (SELECT permisos)",
        "tablas": "permisos",
        "coleccion": [
            ("GET", "/permisos", "authorizePermission('permisos.view')"),
            ("GET", "/permisos/modulo/:modulo", "authorizePermission('permisos.view')"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("500 error interno",),
        ],
        "ramas": [],
    },
    {
        "id": "empresa",
        "titulo": "Empresas / Empresas",
        "modulo": "empresa",
        "desc": "CRUD de empresas + seleccionar empresa activa (multiempresa).",
        "servicio": "empresa.service.ts (backend) · empresa.repo.ts",
        "reparar": "empresa.repo.ts (CRUD SQL)",
        "tablas": "empresas",
        "coleccion": [
            ("POST", "/empresas/seleccionar", "authorizePermission('empresas.view') + validateBody"),
            ("GET", "/empresas", "authorizePermission('empresas.view')"),
            ("GET", "/empresas/:id", "authorizePermission('empresas.view') + validateParams"),
            ("POST", "/empresas", "authorizePermission('empresas.create') + validateBody"),
            ("PUT", "/empresas/:id", "authorizePermission('empresas.edit') + validateBody"),
            ("DELETE", "/empresas/:id", "authorizePermission('empresas.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 empresa no existe",),
            ("409 NIT duplicado / FK",),
            ("500 error interno",),
        ],
        "ramas": [
            ("401 UNAUTHORIZED", "¿Existe la sesion actual (seleccionar)?", "No se pudo identificar la sesion actual."),
            ("404 NOT_FOUND", "¿Existe la empresa solicitada?", "La empresa no existe."),
            ("403 FORBIDDEN", "¿La empresa esta activa (seleccionar)?", "La empresa esta inactiva. No puedes seleccionarla."),
            ("409 CONFLICT", "¿Ya existe una empresa con ese NIT?", "Ya existe una empresa con ese NIT."),
            ("500 INTERNAL_ERROR", "¿Existe el rol Administrador al crear?", "No existe el rol Administrador en el sistema."),
        ],
    },
    {
        "id": "categoria",
        "titulo": "Categorias / Categorias",
        "modulo": "categoria",
        "desc": "CRUD de categorias de productos.",
        "servicio": "categoria.service.ts (frontend) · categoria.repo.ts",
        "reparar": "categoria.repo.ts (CRUD SQL)",
        "tablas": "categorias",
        "coleccion": [
            ("GET", "/categorias", "authorizePermission('categorias.view')"),
            ("GET", "/categorias/:id", "authorizePermission('categorias.view') + validateParams"),
            ("POST", "/categorias", "authorizePermission('categorias.create') + validateBody"),
            ("PUT", "/categorias/:id", "authorizePermission('categorias.edit') + validateBody"),
            ("DELETE", "/categorias/:id", "authorizePermission('categorias.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 categoria no existe",),
            ("409 nombre duplicado / FK",),
            ("500 error interno",),
        ],
        "ramas": [
            ("409 CONFLICT", "¿Ya existe una categoria con ese nombre?", "Ya existe una categoria con ese nombre."),
            ("404 NOT_FOUND", "¿Existe la categoria solicitada?", "La categoria no existe."),
        ],
    },
    {
        "id": "bodega",
        "titulo": "Bodegas / Bodegas",
        "modulo": "bodega",
        "desc": "CRUD de bodegas (almacenes).",
        "servicio": "bodega.service.ts (frontend) · bodega.repo.ts",
        "reparar": "bodega.repo.ts (CRUD SQL)",
        "tablas": "bodegas",
        "coleccion": [
            ("GET", "/bodegas", "authorizePermission('bodegas.view')"),
            ("GET", "/bodegas/:id", "authorizePermission('bodegas.view') + validateParams"),
            ("POST", "/bodegas", "authorizePermission('bodegas.create') + validateBody"),
            ("PUT", "/bodegas/:id", "authorizePermission('bodegas.edit') + validateBody"),
            ("DELETE", "/bodegas/:id", "authorizePermission('bodegas.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 bodega no existe",),
            ("409 nombre/codigo duplicado / FK",),
            ("500 error interno",),
        ],
        "ramas": [
            ("409 CONFLICT", "¿Ya existe una bodega con ese codigo?", "Ya existe una bodega con ese codigo."),
            ("404 NOT_FOUND", "¿Existe la bodega solicitada?", "La bodega no existe."),
        ],
    },
    {
        "id": "producto",
        "titulo": "Productos / Productos",
        "modulo": "producto",
        "desc": "CRUD de productos + listado stock-bajo + detalle + actualizar precio/cantidad + eliminar.",
        "servicio": "producto.service.ts (frontend) · producto.repo.ts",
        "reparar": "producto.repo.ts (CRUD + joins categoria/bodega + stock-bajo)",
        "tablas": "productos · categorias · bodegas",
        "coleccion": [
            ("GET", "/productos", "authorizePermission('productos.view')"),
            ("GET", "/productos/stock-bajo", "authorizePermission('inventario.view')"),
            ("GET", "/productos/:id", "authorizePermission('productos.view') + validateParams"),
            ("POST", "/productos", "authorizePermission('productos.create') + validateBody"),
            ("PUT", "/productos/:id", "authorizePermission('productos.edit') + validateBody"),
            ("PATCH", "/productos/:id/estado", "authorizePermission('productos.edit') + validateBody"),
            ("DELETE", "/productos/:id", "authorizePermission('productos.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 producto no existe",),
            ("409 codigo duplicado / FK",),
            ("500 error interno",),
        ],
        "ramas": [
            ("409 CONFLICT", "¿Ya existe un producto con ese codigo?", "Ya existe un producto con ese codigo."),
            ("404 NOT_FOUND", "¿Existe el producto solicitado?", "El producto no existe."),
        ],
    },
    {
        "id": "movimiento",
        "titulo": "Movimientos / Movimientos de Inventario",
        "modulo": "movimiento",
        "desc": "Movimientos de inventario: listar con filtros, detalle, crear (entrada/salida/transferencia) y eliminar.",
        "servicio": "movimiento.service.ts (frontend) · movimiento.repo.ts",
        "reparar": "movimiento.repo.ts (query + insert + joins producto/bodega)",
        "tablas": "movimientos_inventario · productos · bodegas",
        "coleccion": [
            ("GET", "/movimientos", "authorizePermission('movimientos.view') + validateQuery"),
            ("GET", "/movimientos/:id", "authorizePermission('movimientos.view') + validateParams"),
            ("POST", "/movimientos", "authorizePermission('recepcion.create') + validateBody"),
            ("DELETE", "/movimientos/:id", "authorizePermission('recepcion.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 movimiento no existe",),
            ("409 FK producto/bodega",),
            ("500 error interno",),
        ],
        "ramas": [
            ("404 NOT_FOUND", "¿Existe el movimiento solicitado?", "El movimiento no existe."),
            ("409 CONFLICT", "¿FK producto/bodega valida al crear?", "La referencia a producto o bodega no existe (FK)."),
        ],
    },
    {
        "id": "recepcion",
        "titulo": "Recepciones / Recepcion de Mercancia",
        "modulo": "recepcion",
        "desc": "Recepcion de mercancia con detalle de productos: listar, detalle, crear, actualizar, eliminar.",
        "servicio": "recepcion.service.ts (frontend) · recepcion.repo.ts",
        "reparar": "recepcion.repo.ts (CRUD + detalle + transaccion)",
        "tablas": "recepciones · recepcion_detalle · productos · usuarios · bodegas",
        "coleccion": [
            ("GET", "/recepciones", "authorizeAnyPermission('recepcion.view','historial.view')"),
            ("GET", "/recepciones/:id", "authorizeAnyPermission('recepcion.view','historial.view') + validateParams"),
            ("POST", "/recepciones", "authorizePermission('recepcion.create') + validateBody"),
            ("PUT", "/recepciones/:id", "authorizePermission('recepcion.edit') + validateBody"),
            ("DELETE", "/recepciones/:id", "authorizePermission('recepcion.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 recepcion no existe",),
            ("409 numero_documento duplicado / FK",),
            ("500 error interno",),
        ],
        "ramas": [
            ("404 NOT_FOUND", "¿Existe la recepcion solicitada?", "La recepcion no existe."),
            ("409 CONFLICT", "¿Ya existe ese numero de documento?", "Ya existe una recepcion con ese documento."),
            ("409 CONFLICT", "¿FK de producto en el detalle?", "Uno de los productos del detalle no existe (FK)."),
            ("500 INTERNAL_ERROR", "¿Fallo al insertar cabecera+detalle?", "Transaccion revertida (ROLLBACK)."),
        ],
    },
    {
        "id": "auditoria",
        "titulo": "Auditorias / Auditoria",
        "modulo": "auditoria",
        "desc": "Registro de auditoria: listar y ver detalle por id.",
        "servicio": "auditoria.service.ts (frontend) · auditoria.repo.ts",
        "reparar": "auditoria.repo.ts (SELECT + join usuarios)",
        "tablas": "auditorias · usuarios",
        "coleccion": [
            ("GET", "/auditorias", "authorizePermission('auditoria.view')"),
            ("GET", "/auditorias/:id", "authorizePermission('auditoria.view') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 registro no existe",),
            ("500 error interno",),
        ],
        "ramas": [
            ("404 NOT_FOUND", "¿Existe el registro de auditoria?", "El registro de auditoria no existe."),
        ],
    },
    {
        "id": "incidencia",
        "titulo": "Incidencias / Incidencias",
        "modulo": "incidencia",
        "desc": "Reporte de incidencias: listar, detalle, crear, actualizar y eliminar.",
        "servicio": "incidencia.service.ts (frontend) · incidencia.repo.ts",
        "reparar": "incidencia.repo.ts (CRUD + joins usuarios)",
        "tablas": "incidencias · usuarios",
        "coleccion": [
            ("GET", "/incidencias", "authorizePermission('incidencias.view')"),
            ("GET", "/incidencias/:id", "authorizePermission('incidencias.view') + validateParams"),
            ("POST", "/incidencias", "authorizePermission('incidencias.create') + validateBody"),
            ("PUT", "/incidencias/:id", "authorizePermission('incidencias.edit') + validateBody"),
            ("DELETE", "/incidencias/:id", "authorizePermission('incidencias.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 incidencia no existe",),
            ("409 FK usuarios",),
            ("500 error interno",),
        ],
        "ramas": [
            ("404 NOT_FOUND", "¿Existe la incidencia solicitada?", "La incidencia no existe."),
        ],
    },
    {
        "id": "mantenimiento",
        "titulo": "Mantenimientos / Mantenimiento",
        "modulo": "mantenimiento",
        "desc": "Mantenimientos de equipos: listar, detalle, crear, actualizar y eliminar.",
        "servicio": "mantenimiento.service.ts (frontend) · mantenimiento.repo.ts",
        "reparar": "mantenimiento.repo.ts (CRUD + joins usuarios)",
        "tablas": "mantenimientos · usuarios",
        "coleccion": [
            ("GET", "/mantenimientos", "authorizePermission('mantenimiento.view')"),
            ("GET", "/mantenimientos/:id", "authorizePermission('mantenimiento.view') + validateParams"),
            ("POST", "/mantenimientos", "authorizePermission('mantenimiento.create') + validateBody"),
            ("PUT", "/mantenimientos/:id", "authorizePermission('mantenimiento.edit') + validateBody"),
            ("DELETE", "/mantenimientos/:id", "authorizePermission('mantenimiento.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 mantenimiento no existe",),
            ("500 error interno",),
        ],
        "ramas": [
            ("404 NOT_FOUND", "¿Existe el mantenimiento solicitado?", "El mantenimiento no existe."),
        ],
    },
    {
        "id": "sesion",
        "titulo": "Sesiones / Sesiones",
        "modulo": "sesion",
        "desc": "Sesiones activas: listar, cerrar todas excepto la actual y eliminar una sesion.",
        "servicio": "sesion.service.ts (frontend) · sesion.repo.ts",
        "reparar": "sesion.repo.ts (SELECT + DELETE sesiones)",
        "tablas": "sesiones · usuarios",
        "coleccion": [
            ("GET", "/sesiones", "authorizePermission('sesiones.view')"),
            ("POST", "/sesiones/cerrar-otras", "authorizePermission('sesiones.delete')"),
            ("DELETE", "/sesiones/:id", "authorizePermission('sesiones.delete') + validateParams"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 sesion no existe",),
            ("500 error interno",),
        ],
        "ramas": [
            ("401 UNAUTHORIZED", "¿Hay sesion actual (sesionId en req.user)?", "No se pudo identificar la sesion actual."),
            ("404 NOT_FOUND", "¿Existe la sesion solicitada?", "La sesion no existe."),
            ("403 FORBIDDEN", "¿Intentas cerrar TU sesion actual?", "No puedes cerrar la sesion actual desde aqui."),
        ],
    },
    {
        "id": "notificacion",
        "titulo": "Notificaciones / Notificaciones",
        "modulo": "notificacion",
        "desc": "Notificaciones: listar, marcar una como leida y marcar todas como leidas.",
        "servicio": "notificacion.service.ts (frontend) · notificacion.repo.ts",
        "reparar": "notificacion.repo.ts (SELECT + UPDATE leida)",
        "tablas": "notificaciones",
        "coleccion": [
            ("GET", "/notificaciones", "authorizePermission('notificaciones.view')"),
            ("PATCH", "/notificaciones/:id/leida", "authorizePermission('notificaciones.view') + validateBody"),
            ("POST", "/notificaciones/leidas", "authorizePermission('notificaciones.view')"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 notificacion no existe",),
            ("500 error interno",),
        ],
        "ramas": [
            ("401 UNAUTHORIZED", "¿Usuario autenticado en la peticion (req.user)?", "No autenticado."),
            ("404 NOT_FOUND", "¿Existe la notificacion solicitada?", "La notificacion no existe."),
        ],
    },
    {
        "id": "configuracion",
        "titulo": "Configuracion / Configuracion del Sistema",
        "modulo": "configuracion",
        "desc": "Configuracion de la sesion: listar y actualizar valores.",
        "servicio": "configuracion.service.ts (frontend) · configuracion.repo.ts",
        "reparar": "configuracion.repo.ts (SELECT + UPSERT clave-valor)",
        "tablas": "configuracion_sistema",
        "coleccion": [
            ("GET", "/configuracion", "authorizePermission('configuracion.view')"),
            ("PUT", "/configuracion", "authorizePermission('configuracion.edit') + validateBody"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("500 error interno",),
        ],
        "ramas": [
            ("400 BAD_REQUEST", "¿Se enviaron configuraciones para actualizar?", "No se enviaron configuraciones para actualizar."),
        ],
    },
    {
        "id": "dashboard",
        "titulo": "Dashboard / Panel Principal",
        "modulo": "dashboard",
        "desc": "Indicadores del dashboard: totales y resumen (productos, stock bajo, inventario, graficas).",
        "servicio": "estadisticas.service.ts (frontend) · dashboard.service.ts (backend)",
        "reparar": "dashboard.service.ts (consultas agregadas SQL)",
        "tablas": "productos · movimientos_inventario · notificaciones · sesiones",
        "coleccion": [
            ("GET", "/dashboard/resumen", "authorizePermission('dashboard.view')"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("500 error interno",),
        ],
        "ramas": [],
    },
    {
        "id": "reporte",
        "titulo": "Reportes / Reportes",
        "modulo": "reporte",
        "desc": "Reportes: inventario, movimientos, stock, auditorias e incidencias.",
        "servicio": "reporte.service.ts (frontend) · reporte.repo.ts",
        "reparar": "reporte.repo.ts (consultas agregadas SQL)",
        "tablas": "productos · movimientos_inventario · auditorias · incidencias",
        "coleccion": [
            ("GET", "/reportes/inventario", "authorizePermission('reportes.view')"),
            ("GET", "/reportes/movimientos", "authorizePermission('reportes.view')"),
            ("GET", "/reportes/stock", "authorizePermission('reportes.view')"),
            ("GET", "/reportes/auditorias", "authorizePermission('reportes.view')"),
            ("GET", "/reportes/incidencias", "authorizePermission('reportes.view')"),
        ],
        "errores": [
            ("400 DTO invalido (Zod)",),
            ("401 token invalido",),
            ("403 sin permiso",),
            ("404 sin datos",),
            ("500 error interno",),
        ],
        "ramas": [
            ("404 NOT_FOUND", "¿Hay datos para ese reporte?", "Sin datos para el reporte solicitado."),
        ],
    },
]